// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	entity "github.com/paincake00/microservices-go/inventory/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// IPartRepository is an autogenerated mock type for the IPartRepository type
type IPartRepository struct {
	mock.Mock
}

type IPartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IPartRepository) EXPECT() *IPartRepository_Expecter {
	return &IPartRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: part
func (_m *IPartRepository) Create(part *entity.Part) error {
	ret := _m.Called(part)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Part) error); ok {
		r0 = rf(part)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IPartRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IPartRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - part *entity.Part
func (_e *IPartRepository_Expecter) Create(part interface{}) *IPartRepository_Create_Call {
	return &IPartRepository_Create_Call{Call: _e.mock.On("Create", part)}
}

func (_c *IPartRepository_Create_Call) Run(run func(part *entity.Part)) *IPartRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Part))
	})
	return _c
}

func (_c *IPartRepository_Create_Call) Return(_a0 error) *IPartRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IPartRepository_Create_Call) RunAndReturn(run func(*entity.Part) error) *IPartRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetPart provides a mock function with given fields: _a0
func (_m *IPartRepository) GetPart(_a0 string) (*entity.Part, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *entity.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Part, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Part); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type IPartRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - _a0 string
func (_e *IPartRepository_Expecter) GetPart(_a0 interface{}) *IPartRepository_GetPart_Call {
	return &IPartRepository_GetPart_Call{Call: _e.mock.On("GetPart", _a0)}
}

func (_c *IPartRepository_GetPart_Call) Run(run func(_a0 string)) *IPartRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IPartRepository_GetPart_Call) Return(_a0 *entity.Part, _a1 error) *IPartRepository_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartRepository_GetPart_Call) RunAndReturn(run func(string) (*entity.Part, error)) *IPartRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: filter
func (_m *IPartRepository) ListParts(filter entity.ListPartsFilter) ([]*entity.Part, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*entity.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.ListPartsFilter) ([]*entity.Part, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(entity.ListPartsFilter) []*entity.Part); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(entity.ListPartsFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type IPartRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - filter entity.ListPartsFilter
func (_e *IPartRepository_Expecter) ListParts(filter interface{}) *IPartRepository_ListParts_Call {
	return &IPartRepository_ListParts_Call{Call: _e.mock.On("ListParts", filter)}
}

func (_c *IPartRepository_ListParts_Call) Run(run func(filter entity.ListPartsFilter)) *IPartRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.ListPartsFilter))
	})
	return _c
}

func (_c *IPartRepository_ListParts_Call) Return(_a0 []*entity.Part, _a1 error) *IPartRepository_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartRepository_ListParts_Call) RunAndReturn(run func(entity.ListPartsFilter) ([]*entity.Part, error)) *IPartRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPartRepository creates a new instance of IPartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPartRepository {
	mock := &IPartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
