// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/paincake00/microservices-go/inventory/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// IPartRepository is an autogenerated mock type for the IPartRepository type
type IPartRepository struct {
	mock.Mock
}

type IPartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IPartRepository) EXPECT() *IPartRepository_Expecter {
	return &IPartRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, part
func (_m *IPartRepository) Create(ctx context.Context, part *entity.Part) (string, error) {
	ret := _m.Called(ctx, part)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Part) (string, error)); ok {
		return rf(ctx, part)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Part) string); ok {
		r0 = rf(ctx, part)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Part) error); ok {
		r1 = rf(ctx, part)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IPartRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - part *entity.Part
func (_e *IPartRepository_Expecter) Create(ctx interface{}, part interface{}) *IPartRepository_Create_Call {
	return &IPartRepository_Create_Call{Call: _e.mock.On("Create", ctx, part)}
}

func (_c *IPartRepository_Create_Call) Run(run func(ctx context.Context, part *entity.Part)) *IPartRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Part))
	})
	return _c
}

func (_c *IPartRepository_Create_Call) Return(_a0 string, _a1 error) *IPartRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Part) (string, error)) *IPartRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function with given fields: ctx
func (_m *IPartRepository) DeleteAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IPartRepository_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type IPartRepository_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IPartRepository_Expecter) DeleteAll(ctx interface{}) *IPartRepository_DeleteAll_Call {
	return &IPartRepository_DeleteAll_Call{Call: _e.mock.On("DeleteAll", ctx)}
}

func (_c *IPartRepository_DeleteAll_Call) Run(run func(ctx context.Context)) *IPartRepository_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IPartRepository_DeleteAll_Call) Return(_a0 error) *IPartRepository_DeleteAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IPartRepository_DeleteAll_Call) RunAndReturn(run func(context.Context) error) *IPartRepository_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetPart provides a mock function with given fields: ctx, partUUID
func (_m *IPartRepository) GetPart(ctx context.Context, partUUID string) (*entity.Part, error) {
	ret := _m.Called(ctx, partUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *entity.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Part, error)); ok {
		return rf(ctx, partUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Part); ok {
		r0 = rf(ctx, partUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, partUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type IPartRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUID string
func (_e *IPartRepository_Expecter) GetPart(ctx interface{}, partUUID interface{}) *IPartRepository_GetPart_Call {
	return &IPartRepository_GetPart_Call{Call: _e.mock.On("GetPart", ctx, partUUID)}
}

func (_c *IPartRepository_GetPart_Call) Run(run func(ctx context.Context, partUUID string)) *IPartRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IPartRepository_GetPart_Call) Return(_a0 *entity.Part, _a1 error) *IPartRepository_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartRepository_GetPart_Call) RunAndReturn(run func(context.Context, string) (*entity.Part, error)) *IPartRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, filter
func (_m *IPartRepository) ListParts(ctx context.Context, filter entity.ListPartsFilter) ([]*entity.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*entity.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ListPartsFilter) ([]*entity.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ListPartsFilter) []*entity.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ListPartsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type IPartRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter entity.ListPartsFilter
func (_e *IPartRepository_Expecter) ListParts(ctx interface{}, filter interface{}) *IPartRepository_ListParts_Call {
	return &IPartRepository_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *IPartRepository_ListParts_Call) Run(run func(ctx context.Context, filter entity.ListPartsFilter)) *IPartRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ListPartsFilter))
	})
	return _c
}

func (_c *IPartRepository_ListParts_Call) Return(_a0 []*entity.Part, _a1 error) *IPartRepository_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartRepository_ListParts_Call) RunAndReturn(run func(context.Context, entity.ListPartsFilter) ([]*entity.Part, error)) *IPartRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPartRepository creates a new instance of IPartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPartRepository {
	mock := &IPartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
