// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/paincake00/microservices-go/order/internal/entity"
	enum "github.com/paincake00/microservices-go/order/internal/entity/enum"

	mock "github.com/stretchr/testify/mock"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

type PaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentService) EXPECT() *PaymentService_Expecter {
	return &PaymentService_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, orderUuid, userUuid, paymentMethod
func (_m *PaymentService) PayOrder(ctx context.Context, orderUuid string, userUuid string, paymentMethod enum.PaymentMethod) (entity.PaymentTransaction, error) {
	ret := _m.Called(ctx, orderUuid, userUuid, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 entity.PaymentTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, enum.PaymentMethod) (entity.PaymentTransaction, error)); ok {
		return rf(ctx, orderUuid, userUuid, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, enum.PaymentMethod) entity.PaymentTransaction); ok {
		r0 = rf(ctx, orderUuid, userUuid, paymentMethod)
	} else {
		r0 = ret.Get(0).(entity.PaymentTransaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, enum.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUuid, userUuid, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUuid string
//   - userUuid string
//   - paymentMethod enum.PaymentMethod
func (_e *PaymentService_Expecter) PayOrder(ctx interface{}, orderUuid interface{}, userUuid interface{}, paymentMethod interface{}) *PaymentService_PayOrder_Call {
	return &PaymentService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUuid, userUuid, paymentMethod)}
}

func (_c *PaymentService_PayOrder_Call) Run(run func(ctx context.Context, orderUuid string, userUuid string, paymentMethod enum.PaymentMethod)) *PaymentService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(enum.PaymentMethod))
	})
	return _c
}

func (_c *PaymentService_PayOrder_Call) Return(_a0 entity.PaymentTransaction, _a1 error) *PaymentService_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentService_PayOrder_Call) RunAndReturn(run func(context.Context, string, string, enum.PaymentMethod) (entity.PaymentTransaction, error)) *PaymentService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
