// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IPaymentService is an autogenerated mock type for the IPaymentService type
type IPaymentService struct {
	mock.Mock
}

type IPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *IPaymentService) EXPECT() *IPaymentService_Expecter {
	return &IPaymentService_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with no fields
func (_m *IPaymentService) PayOrder() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPaymentService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type IPaymentService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
func (_e *IPaymentService_Expecter) PayOrder() *IPaymentService_PayOrder_Call {
	return &IPaymentService_PayOrder_Call{Call: _e.mock.On("PayOrder")}
}

func (_c *IPaymentService_PayOrder_Call) Run(run func()) *IPaymentService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IPaymentService_PayOrder_Call) Return(_a0 string, _a1 error) *IPaymentService_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPaymentService_PayOrder_Call) RunAndReturn(run func() (string, error)) *IPaymentService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPaymentService creates a new instance of IPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPaymentService {
	mock := &IPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
