// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/paincake00/microservices-go/inventory/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// IPartService is an autogenerated mock type for the IPartService type
type IPartService struct {
	mock.Mock
}

type IPartService_Expecter struct {
	mock *mock.Mock
}

func (_m *IPartService) EXPECT() *IPartService_Expecter {
	return &IPartService_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: ctx, partUUID
func (_m *IPartService) GetPart(ctx context.Context, partUUID string) (*entity.Part, error) {
	ret := _m.Called(ctx, partUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *entity.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Part, error)); ok {
		return rf(ctx, partUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Part); ok {
		r0 = rf(ctx, partUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, partUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartService_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type IPartService_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUID string
func (_e *IPartService_Expecter) GetPart(ctx interface{}, partUUID interface{}) *IPartService_GetPart_Call {
	return &IPartService_GetPart_Call{Call: _e.mock.On("GetPart", ctx, partUUID)}
}

func (_c *IPartService_GetPart_Call) Run(run func(ctx context.Context, partUUID string)) *IPartService_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IPartService_GetPart_Call) Return(_a0 *entity.Part, _a1 error) *IPartService_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartService_GetPart_Call) RunAndReturn(run func(context.Context, string) (*entity.Part, error)) *IPartService_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, filter
func (_m *IPartService) ListParts(ctx context.Context, filter entity.ListPartsFilter) ([]*entity.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*entity.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ListPartsFilter) ([]*entity.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ListPartsFilter) []*entity.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ListPartsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartService_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type IPartService_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter entity.ListPartsFilter
func (_e *IPartService_Expecter) ListParts(ctx interface{}, filter interface{}) *IPartService_ListParts_Call {
	return &IPartService_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *IPartService_ListParts_Call) Run(run func(ctx context.Context, filter entity.ListPartsFilter)) *IPartService_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ListPartsFilter))
	})
	return _c
}

func (_c *IPartService_ListParts_Call) Return(_a0 []*entity.Part, _a1 error) *IPartService_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartService_ListParts_Call) RunAndReturn(run func(context.Context, entity.ListPartsFilter) ([]*entity.Part, error)) *IPartService_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPartService creates a new instance of IPartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPartService {
	mock := &IPartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
