syntax = 'proto3';

package payment.v1;

option go_package = "github.com/paincake00/microservices-go/shared/pkg/proto/payment/v1;paymentv1";

service PaymentService {
  rpc PayOrder(PayOrderRequest) returns (PayOrderResponse);
}

// PayOrderRequest описывает входные данные для метода PayOrder
message PayOrderRequest {
  string order_uuid = 1;
  string user_uuid = 2;
  PaymentMethod payment_method = 3;
}

// PayOrderResponse описывает выходные данные для метода PayOrder
message PayOrderResponse {
  string transaction_uuid = 1;
}

// PaymentMethod перечисляет возможные методы оплаты заказа
enum PaymentMethod {
  PAYMENT_METHOD_UNSPECIFIED = 0;
  PAYMENT_METHOD_CARD = 1;
  PAYMENT_METHOD_SBP = 2;
  PAYMENT_METHOD_CREDIT_CARD = 3;
  PAYMENT_METHOD_INVESTOR_MONEY = 4;
}