// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	entity "github.com/paincake00/microservices-go/order/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// IOrderRepository is an autogenerated mock type for the IOrderRepository type
type IOrderRepository struct {
	mock.Mock
}

type IOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IOrderRepository) EXPECT() *IOrderRepository_Expecter {
	return &IOrderRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: orderUUID
func (_m *IOrderRepository) Get(orderUUID string) (entity.Order, error) {
	ret := _m.Called(orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entity.Order, error)); ok {
		return rf(orderUUID)
	}
	if rf, ok := ret.Get(0).(func(string) entity.Order); ok {
		r0 = rf(orderUUID)
	} else {
		r0 = ret.Get(0).(entity.Order)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IOrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - orderUUID string
func (_e *IOrderRepository_Expecter) Get(orderUUID interface{}) *IOrderRepository_Get_Call {
	return &IOrderRepository_Get_Call{Call: _e.mock.On("Get", orderUUID)}
}

func (_c *IOrderRepository_Get_Call) Run(run func(orderUUID string)) *IOrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IOrderRepository_Get_Call) Return(_a0 entity.Order, _a1 error) *IOrderRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrderRepository_Get_Call) RunAndReturn(run func(string) (entity.Order, error)) *IOrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: order
func (_m *IOrderRepository) Save(order entity.Order) {
	_m.Called(order)
}

// IOrderRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type IOrderRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - order entity.Order
func (_e *IOrderRepository_Expecter) Save(order interface{}) *IOrderRepository_Save_Call {
	return &IOrderRepository_Save_Call{Call: _e.mock.On("Save", order)}
}

func (_c *IOrderRepository_Save_Call) Run(run func(order entity.Order)) *IOrderRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.Order))
	})
	return _c
}

func (_c *IOrderRepository_Save_Call) Return() *IOrderRepository_Save_Call {
	_c.Call.Return()
	return _c
}

func (_c *IOrderRepository_Save_Call) RunAndReturn(run func(entity.Order)) *IOrderRepository_Save_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function with given fields: order
func (_m *IOrderRepository) Update(order entity.Order) {
	_m.Called(order)
}

// IOrderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type IOrderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - order entity.Order
func (_e *IOrderRepository_Expecter) Update(order interface{}) *IOrderRepository_Update_Call {
	return &IOrderRepository_Update_Call{Call: _e.mock.On("Update", order)}
}

func (_c *IOrderRepository_Update_Call) Run(run func(order entity.Order)) *IOrderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.Order))
	})
	return _c
}

func (_c *IOrderRepository_Update_Call) Return() *IOrderRepository_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *IOrderRepository_Update_Call) RunAndReturn(run func(entity.Order)) *IOrderRepository_Update_Call {
	_c.Run(run)
	return _c
}

// NewIOrderRepository creates a new instance of IOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOrderRepository {
	mock := &IOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
