name: microservices-go

services:
  order-postgres:
    image: ${POSTGRES_IMAGE}
    container_name: order-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${EXTERNAL_POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - order-pgdata:/var/lib/postgresql/data
    restart:
      unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s # проверка с периодичностью 10 сек
      timeout: 5s # ожидание не более 5 сек
      retries: 5 # столько доступно неудачных попыток
    networks:
      - microservices-go-net

  order:
    build:
      context: ../../..
      dockerfile: deploy/docker/order/Dockerfile
    env_file:
      - .env
    environment:
      CONFIG_PATH: /app/config/.env
    volumes:
      - ./.env:/app/config/.env:ro
    ports:
      - "127.0.0.1:${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${HTTP_SERVER_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - microservices-go-net

networks:
  microservices-go-net:
    external: true

volumes:
  order-pgdata: