name: microservices-go

services:
  order-postgres:
    image: ${POSTGRES_IMAGE}
    container_name: order-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - order-pgdata:/var/lib/postgresql/data
    restart:
      unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s # проверка с периодичностью 10 сек
      timeout: 5s # ожидание не более 5 сек
      retries: 5 # столько доступно неудачных попыток
    networks:
      - microservices-go-net

networks:
  microservices-go-net:
    external: true

volumes:
  order-pgdata: