// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// CancelOrderByUuidNoContent is response for CancelOrderByUuid operation.
type CancelOrderByUuidNoContent struct{}

func (*CancelOrderByUuidNoContent) cancelOrderByUuidRes() {}

// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ConflictError) cancelOrderByUuidRes() {}

// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// UUID пользователя.
	UserUUID  string   `json:"user_uuid"`
	PartUuids []string `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []string {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []string) {
	s.PartUuids = val
}

// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	// UUID заказа.
	OrderUUID string `json:"order_uuid"`
	// Стоимость всех деталей в заказе.
	TotalPrice float64 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() string {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val string) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #/components/schemas/generic_error
type GenericError struct {
	// HTTP-код ошибки.
	Code OptInt `json:"code"`
	// Описание ошибки.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val OptString) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Ref: #/components/schemas/internal_error
type InternalError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalError) SetMessage(val string) {
	s.Message = val
}

func (*InternalError) cancelOrderByUuidRes() {}
func (*InternalError) createOrderRes()       {}
func (*InternalError) getOrderByUuidRes()    {}
func (*InternalError) payOrderRes()          {}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) cancelOrderByUuidRes() {}
func (*NotFoundError) createOrderRes()       {}
func (*NotFoundError) getOrderByUuidRes()    {}
func (*NotFoundError) payOrderRes()          {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/order_by_uuid_response
type OrderByUUIDResponse struct {
	// UUID заказа.
	OrderUUID string `json:"order_uuid"`
	// UUID пользователя.
	UserUUID  string   `json:"user_uuid"`
	PartUuids []string `json:"part_uuids"`
	// Стоимость всех деталей в заказе.
	TotalPrice float64 `json:"total_price"`
	// UUID детали.
	TransactionUUID string            `json:"transaction_uuid"`
	PaymentMethod   PaymentMethodEnum `json:"payment_method"`
	Status          OrderStatusEnum   `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *OrderByUUIDResponse) GetOrderUUID() string {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *OrderByUUIDResponse) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *OrderByUUIDResponse) GetPartUuids() []string {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *OrderByUUIDResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderByUUIDResponse) GetTransactionUUID() string {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *OrderByUUIDResponse) GetPaymentMethod() PaymentMethodEnum {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *OrderByUUIDResponse) GetStatus() OrderStatusEnum {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *OrderByUUIDResponse) SetOrderUUID(val string) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *OrderByUUIDResponse) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *OrderByUUIDResponse) SetPartUuids(val []string) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *OrderByUUIDResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderByUUIDResponse) SetTransactionUUID(val string) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *OrderByUUIDResponse) SetPaymentMethod(val PaymentMethodEnum) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *OrderByUUIDResponse) SetStatus(val OrderStatusEnum) {
	s.Status = val
}

func (*OrderByUUIDResponse) getOrderByUuidRes() {}

// Ref: #/components/schemas/order_status_enum
type OrderStatusEnum string

const (
	OrderStatusEnumPENDINGPAYMENT OrderStatusEnum = "PENDING_PAYMENT"
	OrderStatusEnumPAID           OrderStatusEnum = "PAID"
	OrderStatusEnumCANCELLED      OrderStatusEnum = "CANCELLED"
)

// AllValues returns all OrderStatusEnum values.
func (OrderStatusEnum) AllValues() []OrderStatusEnum {
	return []OrderStatusEnum{
		OrderStatusEnumPENDINGPAYMENT,
		OrderStatusEnumPAID,
		OrderStatusEnumCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatusEnum) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusEnumPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusEnumPAID:
		return []byte(s), nil
	case OrderStatusEnumCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatusEnum) UnmarshalText(data []byte) error {
	switch OrderStatusEnum(data) {
	case OrderStatusEnumPENDINGPAYMENT:
		*s = OrderStatusEnumPENDINGPAYMENT
		return nil
	case OrderStatusEnumPAID:
		*s = OrderStatusEnumPAID
		return nil
	case OrderStatusEnumCANCELLED:
		*s = OrderStatusEnumCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/pay_order_request
type PayOrderRequest struct {
	PaymentMethod PaymentMethodEnum `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PaymentMethodEnum {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PaymentMethodEnum) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/pay_order_response
type PayOrderResponse struct {
	// UUID детали.
	TransactionUUID string `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() string {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val string) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}

// Ref: #/components/schemas/payment_method_enum
type PaymentMethodEnum string

const (
	PaymentMethodEnumPAYMENTMETHODUNSPECIFIED   PaymentMethodEnum = "PAYMENT_METHOD_UNSPECIFIED"
	PaymentMethodEnumPAYMENTMETHODCARD          PaymentMethodEnum = "PAYMENT_METHOD_CARD"
	PaymentMethodEnumPAYMENTMETHODSBP           PaymentMethodEnum = "PAYMENT_METHOD_SBP"
	PaymentMethodEnumPAYMENTMETHODCREDITCARD    PaymentMethodEnum = "PAYMENT_METHOD_CREDIT_CARD"
	PaymentMethodEnumPAYMENTMETHODINVESTORMONEY PaymentMethodEnum = "PAYMENT_METHOD_INVESTOR_MONEY"
)

// AllValues returns all PaymentMethodEnum values.
func (PaymentMethodEnum) AllValues() []PaymentMethodEnum {
	return []PaymentMethodEnum{
		PaymentMethodEnumPAYMENTMETHODUNSPECIFIED,
		PaymentMethodEnumPAYMENTMETHODCARD,
		PaymentMethodEnumPAYMENTMETHODSBP,
		PaymentMethodEnumPAYMENTMETHODCREDITCARD,
		PaymentMethodEnumPAYMENTMETHODINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethodEnum) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodEnumPAYMENTMETHODUNSPECIFIED:
		return []byte(s), nil
	case PaymentMethodEnumPAYMENTMETHODCARD:
		return []byte(s), nil
	case PaymentMethodEnumPAYMENTMETHODSBP:
		return []byte(s), nil
	case PaymentMethodEnumPAYMENTMETHODCREDITCARD:
		return []byte(s), nil
	case PaymentMethodEnumPAYMENTMETHODINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethodEnum) UnmarshalText(data []byte) error {
	switch PaymentMethodEnum(data) {
	case PaymentMethodEnumPAYMENTMETHODUNSPECIFIED:
		*s = PaymentMethodEnumPAYMENTMETHODUNSPECIFIED
		return nil
	case PaymentMethodEnumPAYMENTMETHODCARD:
		*s = PaymentMethodEnumPAYMENTMETHODCARD
		return nil
	case PaymentMethodEnumPAYMENTMETHODSBP:
		*s = PaymentMethodEnumPAYMENTMETHODSBP
		return nil
	case PaymentMethodEnumPAYMENTMETHODCREDITCARD:
		*s = PaymentMethodEnumPAYMENTMETHODCREDITCARD
		return nil
	case PaymentMethodEnumPAYMENTMETHODINVESTORMONEY:
		*s = PaymentMethodEnumPAYMENTMETHODINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
