// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/paincake00/microservices-go/order/internal/entity"
	enum "github.com/paincake00/microservices-go/order/internal/entity/enum"
	mock "github.com/stretchr/testify/mock"
)

// IOrderService is an autogenerated mock type for the IOrderService type
type IOrderService struct {
	mock.Mock
}

type IOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *IOrderService) EXPECT() *IOrderService_Expecter {
	return &IOrderService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, orderUUID
func (_m *IOrderService) Cancel(ctx context.Context, orderUUID string) error {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IOrderService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type IOrderService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *IOrderService_Expecter) Cancel(ctx interface{}, orderUUID interface{}) *IOrderService_Cancel_Call {
	return &IOrderService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, orderUUID)}
}

func (_c *IOrderService_Cancel_Call) Run(run func(ctx context.Context, orderUUID string)) *IOrderService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IOrderService_Cancel_Call) Return(_a0 error) *IOrderService_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IOrderService_Cancel_Call) RunAndReturn(run func(context.Context, string) error) *IOrderService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userUUID, partUUIDs
func (_m *IOrderService) Create(ctx context.Context, userUUID string, partUUIDs []string) (entity.OrderCompleted, error) {
	ret := _m.Called(ctx, userUUID, partUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.OrderCompleted
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (entity.OrderCompleted, error)); ok {
		return rf(ctx, userUUID, partUUIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) entity.OrderCompleted); ok {
		r0 = rf(ctx, userUUID, partUUIDs)
	} else {
		r0 = ret.Get(0).(entity.OrderCompleted)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, userUUID, partUUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IOrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - partUUIDs []string
func (_e *IOrderService_Expecter) Create(ctx interface{}, userUUID interface{}, partUUIDs interface{}) *IOrderService_Create_Call {
	return &IOrderService_Create_Call{Call: _e.mock.On("Create", ctx, userUUID, partUUIDs)}
}

func (_c *IOrderService_Create_Call) Run(run func(ctx context.Context, userUUID string, partUUIDs []string)) *IOrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *IOrderService_Create_Call) Return(_a0 entity.OrderCompleted, _a1 error) *IOrderService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrderService_Create_Call) RunAndReturn(run func(context.Context, string, []string) (entity.OrderCompleted, error)) *IOrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUuid provides a mock function with given fields: ctx, orderUUID
func (_m *IOrderService) GetByUuid(ctx context.Context, orderUUID string) (entity.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUuid")
	}

	var r0 entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(entity.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrderService_GetByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUuid'
type IOrderService_GetByUuid_Call struct {
	*mock.Call
}

// GetByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *IOrderService_Expecter) GetByUuid(ctx interface{}, orderUUID interface{}) *IOrderService_GetByUuid_Call {
	return &IOrderService_GetByUuid_Call{Call: _e.mock.On("GetByUuid", ctx, orderUUID)}
}

func (_c *IOrderService_GetByUuid_Call) Run(run func(ctx context.Context, orderUUID string)) *IOrderService_GetByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IOrderService_GetByUuid_Call) Return(_a0 entity.Order, _a1 error) *IOrderService_GetByUuid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrderService_GetByUuid_Call) RunAndReturn(run func(context.Context, string) (entity.Order, error)) *IOrderService_GetByUuid_Call {
	_c.Call.Return(run)
	return _c
}

// Pay provides a mock function with given fields: ctx, orderUUID, payMethod
func (_m *IOrderService) Pay(ctx context.Context, orderUUID string, payMethod enum.PaymentMethod) (entity.PaymentTransaction, error) {
	ret := _m.Called(ctx, orderUUID, payMethod)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 entity.PaymentTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, enum.PaymentMethod) (entity.PaymentTransaction, error)); ok {
		return rf(ctx, orderUUID, payMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, enum.PaymentMethod) entity.PaymentTransaction); ok {
		r0 = rf(ctx, orderUUID, payMethod)
	} else {
		r0 = ret.Get(0).(entity.PaymentTransaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, enum.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUUID, payMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrderService_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type IOrderService_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - payMethod enum.PaymentMethod
func (_e *IOrderService_Expecter) Pay(ctx interface{}, orderUUID interface{}, payMethod interface{}) *IOrderService_Pay_Call {
	return &IOrderService_Pay_Call{Call: _e.mock.On("Pay", ctx, orderUUID, payMethod)}
}

func (_c *IOrderService_Pay_Call) Run(run func(ctx context.Context, orderUUID string, payMethod enum.PaymentMethod)) *IOrderService_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(enum.PaymentMethod))
	})
	return _c
}

func (_c *IOrderService_Pay_Call) Return(_a0 entity.PaymentTransaction, _a1 error) *IOrderService_Pay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrderService_Pay_Call) RunAndReturn(run func(context.Context, string, enum.PaymentMethod) (entity.PaymentTransaction, error)) *IOrderService_Pay_Call {
	_c.Call.Return(run)
	return _c
}

// NewIOrderService creates a new instance of IOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOrderService {
	mock := &IOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
