name: microservices-go

services:
  inventory-mongo:
    image: ${MONGO_IMAGE}
    container_name: inventory-mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_inventory_data:/data/db
    ports:
      - "127.0.0.1:${EXTERNAL_MONGO_PORT}:${MONGO_PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase ${MONGO_AUTH_DB}",
        ]
      # Проверка готовности MongoDB: выполняем команду ping через mongosh с указанием логина и пароля
      # --quiet отключает лишний вывод, чтобы результатом был только "1" при успехе
      interval: 10s # Запускаем проверку каждые 10 секунд
      timeout: 5s # Максимальное время ожидания выполнения ping-команды
      retries: 5 # После 5 неудачных проверок подряд контейнер считается "неработоспособным"
    restart:
      unless-stopped
    networks:
      - microservices-go-net

  inventory:
    build:
      context: ../../..
      dockerfile: deploy/docker/inventory/Dockerfile
    environment:
      CONFIG_PATH: /app/config/.env
    env_file:
      - .env
    volumes:
        - ./.env:/app/config/.env:ro
    ports:
      - "127.0.0.1:${GRPC_PORT}:${GRPC_PORT}"
    healthcheck:
      test: [ "CMD", "grpc-health-probe", "-addr=:${GRPC_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - microservices-go-net

networks:
  microservices-go-net:
    external: true

volumes:
  mongo_inventory_data: